#######################################################
#  logs file input
#######################################################
filebeat.inputs:
  - type: log
    paths:
      - /tmp/test-data/*/*
#    json.keys_under_root: true
#    json.add_error_key: true

#######################################################
#  Logstash output to transform and prepare logs
#######################################################
output.logstash:
  hosts: ["logstash:5044"]
  
# output.console:
  # pretty: true